---
  # Create and run EC2 Instance
- name: Create Test EC2
  hosts: localhost
  gather_facts: False
  vars:
    keypair: my_keypair
    instance_type: t2.micro
    image: ubuntu
    region: us-west-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: default
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2